### ISSUE TITLE
有没有办法设置多个密码

### ISSUE THREAD

**Issue by Anpiluo** [crazypeace/Url-Shorten-Worker#1]
有没有办法设置多个密码
或者干脆把这个密码去掉，只看目录，目录对了就让进，然后我自己再单独套一层cf access。
不然如果我把密码分享给别人，之后又不想让他用了，只能换一个密码，如果又有其他人用就太麻烦了。

**Comment by crazypeace** [comment]
代码在这里
https://github.com/crazypeace/Url-Shorten-Worker/blob/main/index.js#L90
多读取几个密钥就行了。

现在目录就是密钥啊，你想套cf access自己套呗
