### ISSUE TITLE
按up主的说明,将creazypeace改成了自己的仓库,页面显示404

### ISSUE THREAD

**Issue by 14link** [crazypeace/Url-Shorten-Worker#12]
为了防止楼主,up主更新,造成不能使用,按着说明,将creazypeace改成了自己的仓库,页面显示404,不能使用啊,大佬,怎么解决?

**Comment by CarrolChen** [comment]
我这边也显示是的呢，昨晚debug了一下，如果不更改let index_html = "https://crazypeace.github.io/Url-Shorten-Worker/" + config.theme + "/index.html"中的用户名为自己，可以成功，你可以试试，但是不是很清楚这样的话，会不会受上游影响，如果受上游影响，那fork到自己仓库将没有任何意义。具体解决方案，可以等大佬有时间看看。
![1](https://github.com/crazypeace/Url-Shorten-Worker/assets/54614118/57611509-23f3-4077-b1af-1121eeaec051)
![2](https://github.com/crazypeace/Url-Shorten-Worker/assets/54614118/85703817-03f3-4b30-a5ec-b40f4dd01d17)

**Comment by langer-zheng** [comment]
问题来于，确保你fork后的GitHub Pages的激活与部署。具体如下：
1. 确保你已经在自己的 GitHub 仓库中激活了 GitHub Pages 功能，并且选择了正确的分支进行部署。GitHub Pages 默认不会自动激活，需要手动设置。
2. 检查你的 GitHub Pages 站点是否已经成功构建。在仓库的 Settings -> Pages 部分可以查看到构建状态。
3. 检查激活状态。输入激活后的链接查看是否成功激活，激活后就可以了：https://你的github名称.github.io/Url-Shorten-Worker/

**Comment by 14link** [comment]
问题已解决,感谢回复.
