### ISSUE TITLE
自己fork部署问题

### ISSUE THREAD

**Issue by zhikanyeye** [crazypeace/Url-Shorten-Worker#18]
为什么我按照教程fork到自己的项目库，改了作者说的地方反而不能用呢？必须是作者原版的workJS才能运行？麻烦看到的大佬帮解答一下，谢谢

**Comment by androidcoderr** [comment]
你仓库并没有**fork**啊

**Comment by zhikanyeye** [comment]
谢谢大哥的回复，我怎么把那个pr删除了，有点尴尬😅

**Comment by androidcoderr** [comment]
删除不了，关闭就行了
