### ISSUE TITLE
API是否可以简化，做到参数可选，兼容原版本。

### ISSUE THREAD

**Issue by befantasy** [crazypeace/Url-Shorten-Worker#3]
新增的功能很实用，但是在调试过程中，发现API新增了几个项，而且是必选。如果是可选，兼容原版就好了。

**Comment by crazypeace** [comment]
你好, 因为我觉得API的设计应该是把错误码和正确的结果区分开, 所以我修改了API的设计. 

原版的设计是, 如果正常, 返回值是缩短后的编码, 如果错误, 返回值是报错.
