### ISSUE TITLE
workers配置 之后 添加不了自定义链接

### ISSUE THREAD

**Issue by plcdbgh** [crazypeace/Url-Shorten-Worker#7]
[
![WeChat57817e381529696b3fd8bf17d95a9002](https://github.com/crazypeace/Url-Shorten-Worker/assets/147619475/9f49ed02-41c4-432f-8fcd-747d04a12de3)
![WeChatd2f8dcc25965c8634d68f204bfba9567](https://github.com/crazypeace/Url-Shorten-Worker/assets/147619475/678e7f72-5153-4b51-a4aa-e8e905e098ca)
](url)

**Comment by plcdbgh** [comment]
![WeChatbaf6cd47ba2a3066e71e4bd694563b12](https://github.com/crazypeace/Url-Shorten-Worker/assets/147619475/f4f22b24-a8a3-43df-970d-fed155d42964)
![WeChatd8257f5a69863038e95bf01113041539](https://github.com/crazypeace/Url-Shorten-Worker/assets/147619475/95f881c8-73a2-4d55-b286-1fb2cbb6ca65)

**Comment by plcdbgh** [comment]
添加第一条是 不管短链接写什么  都会变成undefined     
添加第二条时 将无法添加

**Comment by crazypeace** [comment]
楼上几位, 抱歉不知为何github没有邮件提醒

-----

代码有更新. 把新的worker.js的内容放到cloudflare里面去就好了.
https://github.com/crazypeace/Url-Shorten-Worker/blob/main/worker.js

-----

还有一个解决方法就是, 如果你以前fork过, 是正常工作的话, cloudflare修改这一行, 改为加载你自己的index.html
![image](https://github.com/crazypeace/Url-Shorten-Worker/assets/665889/ef22d07f-c396-48aa-a941-7a7526279b45)

你自己的repo呢, 修改index.html, 改为加载你自己的main.js
![image](https://github.com/crazypeace/Url-Shorten-Worker/assets/665889/cfb0f370-ea38-4427-a608-bb00fa14e625)
